name: SocialCitizens
main: me.bman7842.socialcitizens.Main
version: 0.36
author: bman7842
description: Social Citizens plugin
commands:
  shout:
    description: Shout a global message
  trade:
    description: Send an item to a player
  news:
    description: Get the current news
  cc:
    description: Clears the chat!
  poke:
    description: Pokes a player!